# Generated by Django 3.1 on 2020-10-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201024_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktransaction',
            name='status',
            field=models.CharField(choices=[('В пользовании', 'Inuse'), ('Сдана', 'Returned'), ('Долг', 'Debt')], default='В пользовании', max_length=15),
        ),
    ]
